### ISSUE TITLE
What is size of bitcoin Block?

### ISSUE THREAD

**Issue by ravirocx** [varadhbhatnagar/Blockchain-Beginning#13]
Size was proposed as 1 MB in 2009 by Satoshi Nakamoto, although controversy is there.

**Comment by varadhbhatnagar** [comment]
As per my limited knowledge. There was no limit on the size of Bitcoin originally but a limit of 1 MB was set later because of problem of Denial of Service Attack.
Denial of Service attack is basically huge blocks of transactions which are not possible to process with current technology.
The Bitcoin community is divided on this issue as some of them say that the block size must be increased in order to make Bitcoin competitive with other currency mediums such as Paypal while others argue that it must be kept constant so that there is less difficulty in mining the block.
You can read more here : https://www.cryptocompare.com/coins/guides/what-is-the-block-size-limit/

**Comment by ravirocx** [comment]
yes Varad, you are inline with my point. The controversy i mentioned is same as you described.
Nakamoto secretly committed size as 1MB to prevent large spam blocks.
